### ISSUE TITLE
Changes in powerthesaurus

### ISSUE THREAD

**Issue by Saulopv** [words/powerthesaurus-api#2]
Hi, so I am failing 3 out of the 6 tests and I am not sure where the problem is... 
Does anyone have the same problem?
Here is the output:
<pre>
Saulo$ node test
TAP version 13
# powerthesaurus
ok 1 is a function
# promises
not ok 2 should have valid results
  ---
    operator: throws
    expected: |-
      undefined
    actual: |-
      { [AssertionError [ERR_ASSERTION]: returns several results] generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' }
    at: check (/Users/Saulo/powerthesa/test.js:46:7)
    stack: |-
      AssertionError [ERR_ASSERTION]: returns several results
          at /Users/Saulo/powerthesa/test.js:47:14
          at Test.doesNotThrow (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:535:9)
          at Test.bound [as doesNotThrow] (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:80:32)
          at check (/Users/Saulo/powerthesa/test.js:46:7)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
# callbacks
ok 3 should not give an error
not ok 4 should have valid results
  ---
    operator: throws
    expected: |-
      undefined
    actual: |-
      { [AssertionError [ERR_ASSERTION]: returns several results] generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' }
    at: check (/Users/Saulo/powerthesa/test.js:46:7)
    stack: |-
      AssertionError [ERR_ASSERTION]: returns several results
          at /Users/Saulo/powerthesa/test.js:47:14
          at Test.doesNotThrow (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:535:9)
          at Test.bound [as doesNotThrow] (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:80:32)
          at check (/Users/Saulo/powerthesa/test.js:46:7)
          at /Users/Saulo/powerthesa/test.js:21:51
          at done (/Users/Saulo/powerthesa/index.js:79:9)
          at onbody (/Users/Saulo/powerthesa/index.js:69:7)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
# kind
not ok 5 should have valid results
  ---
    operator: throws
    expected: |-
      undefined
    actual: |-
      { [AssertionError [ERR_ASSERTION]: returns several results] generatedMessage: false, code: 'ERR_ASSERTION', actual: false, expected: true, operator: '==' }
    at: check (/Users/Saulo/powerthesa/test.js:46:7)
    stack: |-
      AssertionError [ERR_ASSERTION]: returns several results
          at /Users/Saulo/powerthesa/test.js:47:14
          at Test.doesNotThrow (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:535:9)
          at Test.bound [as doesNotThrow] (/Users/Saulo/powerthesa/node_modules/tape/lib/test.js:80:32)
          at check (/Users/Saulo/powerthesa/test.js:46:7)
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
# invalid kind
ok 6 should pass an error

1..6
# tests 6
# pass  3
# fail  3

**Comment by wooorm** [comment]
Unfortunately they completely changed their website.
